# Generated by Django 5.1.5 on 2025-01-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_status'),
        ('student', '0008_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='payment_method',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentreceived',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_received_student', to='student.student'),
        ),
        migrations.CreateModel(
            name='PaymentPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_pending_student', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
