# Generated by Django 5.1.5 on 2025-02-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentreceived_amount_paid_and_more'),
        ('student', '0009_student_billing_method_student_monthly_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_delay_student', to='student.student')),
            ],
        ),
    ]
