# Generated by Django 5.1.5 on 2025-01-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_pendingpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
    ]
