# Generated by Django 5.1.5 on 2025-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdelay',
            name='value_delay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
