# Generated by Django 5.1.5 on 2025-02-12 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentdelay_value_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdelay',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
