# Generated by Django 5.1.5 on 2025-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentdelay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdelay',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
