# Generated by Django 5.1.5 on 2025-02-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentdelay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='payment_source',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
