# Generated by Django 5.1.5 on 2025-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.TextField(max_length=400),
        ),
    ]
