# Generated by Django 5.1.5 on 2025-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'pendente')], max_length=40),
        ),
    ]
