# Generated by Django 5.1.5 on 2025-02-05 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
