# Generated by Django 5.1.5 on 2025-02-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_installment_created_at_installment_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='date_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
