# Generated by Django 5.1.5 on 2025-02-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_installment_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='expense.expense'),
        ),
    ]
