# Generated by Django 5.1.5 on 2025-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=20)),
                ('class_days', models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'sexta-feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('class_quantity', models.IntegerField()),
                ('class_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('I', 'I'), ('PRO', 'PRO')], max_length=3)),
                ('due_date', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Parou', 'Parou'), ('Novo', 'Novo'), ('Retornou', 'Retornou')], default='Novo', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_att', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
