# Generated by Django 5.1.5 on 2025-01-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_days',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
    ]
