# Generated by Django 5.1.5 on 2025-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_class_days_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Parou', 'Parou'), ('Novo', 'Novo'), ('Retornou', 'Retornou')], max_length=50, null=True),
        ),
    ]
