# Generated by Django 5.1.5 on 2025-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
