# Generated by Django 5.1.5 on 2025-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status_payment',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('pago', 'Pago')], max_length=50, null=True),
        ),
    ]
