# Generated by Django 5.1.5 on 2025-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_class_quantity_alter_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': [models.Case(models.When(status='Parou', then=models.Value(1)), models.When(status='Retornou', then=models.Value(2)), models.When(status='Novo', then=models.Value(3)), models.When(status='Regular', then=models.Value(4)), default=models.Value(5), output_field=models.IntegerField())]},
        ),
    ]
