# Generated by Django 5.1.5 on 2025-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': [models.Case(models.When(status='Parou', then=models.Value(4)), models.When(status='Retornou', then=models.Value(3)), models.When(status='Novo', then=models.Value(2)), models.When(status='Regular', then=models.Value(1)), default=models.Value(5), output_field=models.IntegerField())]},
        ),
    ]
