# Generated by Django 5.1.5 on 2025-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='billing_method',
            field=models.CharField(choices=[('aula', 'Aula'), ('mensal', 'Mensal')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
