# Generated by Django 5.1.5 on 2025-02-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0009_student_billing_method_student_monthly_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.CharField(choices=[('seg', 'Segunda-Feira'), ('ter', 'Terça-Feira'), ('qua', 'Quarta-Feira'), ('qui', 'Quinta-Feira'), ('sex', 'Sexta-Feira'), ('sab', 'Sabádo'), ('dom', 'Domingo')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_training', to='training.locationtraining')),
                ('student', models.ManyToManyField(related_name='student_training', to='student.student')),
            ],
        ),
    ]
