# Generated by Django 5.1.5 on 2025-02-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_billing_method_student_monthly_fee_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingclass',
            options={'ordering': ['day', 'time']},
        ),
        migrations.AddField(
            model_name='locationtraining',
            name='quantity_training',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trainingclass',
            name='student',
            field=models.ManyToManyField(related_name='training_classes', to='student.student'),
        ),
    ]
